name: Jekyll

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/jekyll:latest /bin/bash -c "export JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} && export PAGES_REPO_NWO=${{ github.repository }} && chmod 777 /srv/jekyll && jekyll build --future"

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
